name: Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Label Pull Request Size
        uses: pascalgn/size-labeler@v0.4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: 10
          s_max_size: 100
          m_max_size: 500
          l_max_size: 1000
